export interface ThemeDefinition {
  name: string;
  label: string;
  retroLayout?: boolean;
  css: Record<string, string>;
}

export const themes: ThemeDefinition[] = [
  {
    name: 'default',
    label: 'CLASSIC',
    retroLayout: true,
    css: {
      '--bg': '#0a0a0a',
      '--surface': 'transparent',
      '--surface-alt': 'transparent',
      '--fg': '#00cc44',
      '--fg-dim': '#006600',
      '--clock-color': '#00ff00',
      '--border-color': 'transparent',
      '--border-radius': '0px',
      '--section-title-color': '#00ff00',
      '--muted': '#007744',
      '--success': '#00ff00',
      '--warning': '#ffcc00',
      '--danger': '#ff0000',
      '--widget-github': '#33cc66',
      '--widget-calendar': '#00bbff',
      '--widget-health': '#00ff00',
      '--font-mono': "'JetBrains Mono', 'Iosevka', 'IBM Plex Mono', 'Fira Code', monospace",
      '--clock-font': "'JetBrains Mono', 'Iosevka', 'IBM Plex Mono', 'Fira Code', monospace",
      '--letter-spacing': '-0.04em',
      '--line-height': '0.9',
      '--date-color': '#00cc44',
      '--hostname-color': '#006600',
      '--workspace-active-bg': '#00aa33',
      '--workspace-active-fg': '#000000',
      '--workspace-inactive-color': '#006600',
      '--github-repo-color': '#33cc66',
      '--github-pr-label': '#66dd88',
      '--github-pr-number': '#e6c87d',
      '--github-pr-title': '#66dd88',
      '--github-issue-label': '#e6c87d',
      '--github-issue-number': '#e6c87d',
      '--github-issue-title': '#66dd88',
      '--github-meta': '#006633',
      '--health-title-color': '#00ff00',
      '--health-check-icon': '#00ff00',
      '--health-warn-icon': '#ffcc00',
      '--health-text': '#00cc44',
      '--calendar-title-color': '#00ff00',
      '--calendar-date-color': '#00bbff',
      '--calendar-time-color': '#33cc66',
      '--calendar-event-color': '#00cc44',
      '--orange': '#ff8800',
      '--yellow': '#e6c87d',
      '--blue': '#00bbff',
      '--green': '#00ff00',
      '--purple': '#66dd88',
      '--gray-blue': '#338855',
      '--text-secondary': '#006633',
    },
  },
  {
    name: 'nerv',
    label: 'NERV',
    retroLayout: true,
    css: {
      '--bg': '#1a0000',
      '--surface': 'transparent',
      '--surface-alt': 'transparent',
      '--fg': '#ff6666',
      '--fg-dim': '#880000',
      '--clock-color': '#ff0000',
      '--border-color': 'transparent',
      '--border-radius': '0px',
      '--section-title-color': '#ffaf00',
      '--muted': '#886666',
      '--success': '#00ff87',
      '--warning': '#ffcc00',
      '--danger': '#ff3366',
      '--widget-github': '#ffaf00',
      '--widget-calendar': '#ff6666',
      '--widget-health': '#00ff87',
      '--font-mono': "'JetBrains Mono', 'Iosevka', 'IBM Plex Mono', 'Fira Code', monospace",
      '--clock-font': "'JetBrains Mono', 'Iosevka', 'IBM Plex Mono', 'Fira Code', monospace",
      '--letter-spacing': '-0.04em',
      '--line-height': '0.9',
      '--date-color': '#ff6666',
      '--hostname-color': '#880000',
      '--workspace-active-bg': '#cc0000',
      '--workspace-active-fg': '#ffffff',
      '--workspace-inactive-color': '#880000',
      '--github-repo-color': '#ff6666',
      '--github-pr-label': '#ff8888',
      '--github-pr-number': '#ffaf00',
      '--github-pr-title': '#ff8888',
      '--github-issue-label': '#ffaf00',
      '--github-issue-number': '#ffaf00',
      '--github-issue-title': '#ff8888',
      '--github-meta': '#884444',
      '--health-title-color': '#ff3333',
      '--health-check-icon': '#00ff87',
      '--health-warn-icon': '#ffcc00',
      '--health-text': '#ff6666',
      '--calendar-title-color': '#ff3333',
      '--calendar-date-color': '#ff6666',
      '--calendar-time-color': '#ff8888',
      '--calendar-event-color': '#ff6666',
      '--orange': '#ff8700',
      '--yellow': '#ffcc00',
      '--blue': '#ff4444',
      '--green': '#00ff87',
      '--purple': '#ff3366',
      '--gray-blue': '#885566',
      '--text-secondary': '#884444',
    },
  },
  {
    name: 'evangelion',
    label: 'EVANGELION',
    retroLayout: true,
    css: {
      '--bg': '#0e0a1a',
      '--surface': 'transparent',
      '--surface-alt': 'transparent',
      '--fg': '#c08aff',
      '--fg-dim': '#7a5fa0',
      '--clock-color': '#af5fff',
      '--border-color': 'transparent',
      '--border-radius': '0px',
      '--section-title-color': '#ff8700',
      '--muted': '#8778aa',
      '--success': '#87ff00',
      '--warning': '#ffcc00',
      '--danger': '#ff3366',
      '--font-mono': "'JetBrains Mono', 'Iosevka', 'IBM Plex Mono', 'Fira Code', monospace",
      '--clock-font': "'JetBrains Mono', 'Iosevka', 'IBM Plex Mono', 'Fira Code', monospace",
      '--letter-spacing': '-0.04em',
      '--line-height': '0.9',
      '--date-color': '#d4a0ff',
      '--hostname-color': '#7a5fa0',
      '--workspace-active-bg': '#875fff',
      '--workspace-active-fg': '#0e0a1a',
      '--workspace-inactive-color': '#7a5fa0',
      '--github-repo-color': '#b080e0',
      '--github-pr-label': '#d8a6d9',
      '--github-pr-number': '#e7c57d',
      '--github-pr-title': '#d4b0e0',
      '--github-issue-label': '#e7c57d',
      '--github-issue-number': '#e7c57d',
      '--github-issue-title': '#d4b0e0',
      '--github-meta': '#8778aa',
      '--health-title-color': '#ff8700',
      '--health-check-icon': '#87ff00',
      '--health-warn-icon': '#ffcc00',
      '--health-text': '#c08aff',
      '--calendar-title-color': '#ff8700',
      '--calendar-date-color': '#af5fff',
      '--calendar-time-color': '#b080e0',
      '--calendar-event-color': '#c08aff',
      '--orange': '#ff8700',
      '--yellow': '#ffcc00',
      '--blue': '#af5fff',
      '--green': '#87ff00',
      '--purple': '#c08aff',
      '--gray-blue': '#8778aa',
      '--text-secondary': '#8778aa',
    },
  },
];

export function getTheme(name: string): ThemeDefinition {
  return themes.find((t) => t.name === name) || themes[0];
}

export function getThemeIndex(name: string): number {
  const idx = themes.findIndex((t) => t.name === name);
  return idx >= 0 ? idx : 0;
}

export function getThemeName(index: number): string {
  return themes[index]?.name || themes[0].name;
}

export function applyThemeCss(name: string): void {
  if (typeof document === 'undefined') return;
  const theme = getTheme(name);
  const root = document.documentElement;
  for (const [key, value] of Object.entries(theme.css)) {
    root.style.setProperty(key, value);
  }
}
